### ISSUE TITLE
[1.18.X]: Payload May not be Larger than 1048576

### ISSUE THREAD

**Issue by aking4125** [someaddons/connectivity#17] opened 2022-03-26 17:22 UTC
### Describe the bug you're experiencing

Hello, upon attempting to connect to a LAN world. The Client receives the error "Payload May not be Larger than 1048576" and the connection terminates. We attempted to use this mod to help with that as it helped for 1.16.5.

![Capture](https://user-images.githubusercontent.com/11141831/160748439-65c9a943-d57d-4dbc-b7e0-3b8a7a846b6f.PNG)

Below are both debug.log files. `debugPrintMessages = true` was enabled for both debug.log files.

### Reproducability

I guess simply attempt to host a LAN world, then have another player or client attempt to connect and it breaks? Perhaps some incompatibility somewhere?

### Mod up to date

We didn't update to 1.18.2 because many of the mods from our pack hasn't updated as of yet. 

### Minecraft version

1.18.1

### Modloader version

Forge

### Logs

[Client debug.log](https://gist.github.com/aking4125/f3c45f114d17ce1808524b6d4467781c)
[Server [LAN Hosted] debug.log](https://gist.github.com/aking4125/77a36ea7449a4f60e01a47a7a271b12c)

`debugPrintMessages = true` was enabled for both debug.log files

**Comment by aking4125** [comment] 2022-03-30 03:58
Sorry for the delay @someaddons. I have updated the original comment with both debug.log files and a screenshot. 

`debugPrintMessages = true` was enabled for both debug.log files

**Comment by someaddons** [comment] 2022-04-08 09:20
lan mode is generally not supported in a modded environment, and may cause these kind of issues. Can you try moving it to a local forge server instead and see if it still happens?

**Comment by aking4125** [comment] 2022-04-30 19:37
Alright. So rebuild the pack and swapped to 1.18.2. Created a dedicated server and...

![image](https://user-images.githubusercontent.com/11141831/166120096-23fdf807-e7fa-4ff5-83d8-ac8599ec71ae.png)

Both Client and server has the same version of Connectivity. 

Server: [debug.log](https://github.com/someaddons/connectivity/files/8597687/debug.log)
Client: [debug.log](https://github.com/someaddons/connectivity/files/8597688/debug.log)

[Connectivity-1.18.2-2.8 [Forge]
](https://www.curseforge.com/minecraft/mc-mods/connectivity/files/3752334)




> lan mode is generally not supported in a modded environment, and may cause these kind of issues. Can you try moving it to a local forge server instead and see if it still happens?

Should point out that in 1.16.5. This isn't an issue, world works on dedicated server and LAN world. It's only 1.18 that seems to be different. But both LAN and Dedicated servers error out with the above issue.

**Comment by someaddons** [comment] 2022-05-02 23:01
Try version 2.9 I just uploaded, think that one should fix it

**Comment by aking4125** [comment] 2022-05-03 08:12
Sorry for the late response. 

Version 2.9 of Connectivity for Forge 1.18.2 works perfectly!

**Comment by someaddons** [comment] 2022-05-03 09:14
nice, seems the payload limit modification didnt take effect as intended before :)

**Closed by someaddons** 2022-05-03 09:14 UTC
Labels: bug
